---
- name: I'm Rick James!
  hosts: all
  gather_facts: false

  tasks:

    - name: Print something cool
      ansible.builtin.debug:
        msg: "I'm Rick James!!"

    - name: Extra_vars - instance type
      ansible.builtin.debug:
        var: instance_type

    - name: Extra_vars - instance id
      ansible.builtin.debug:
        var: instance_id

    - name: Extra_vars - ec2 region
      ansible.builtin.debug:
        var: ec2_region

    - name: Gather information about a particular instance using it's instance ID
      amazon.aws.ec2_instance_info:
        region: "{{ ec2_region | regex_search('(?<=::)[^::]*') }}"
        instance_ids:
          - "{{ instance_id }}"
      register: resize_ec2_instance_vm_info

    - name: Dump out the Ec2 information
      ansible.builtin.debug:
        msg: "{{ resize_ec2_instance_vm_info }}"