---
- name: I'm Rick James!
  hosts: localhost
  gather_facts: false
  vars:
    ocp_dep: foo
    ocp_ns: bar

  tasks:

    - name: Extra vars ocp_namespace
      ansible.builtin.debug:
        var: ocp_ns

    - name: Extra vars ocp_dep
      ansible.builtin.debug:
        var: ocp_dep

    - name: Print something cool
      ansible.builtin.debug:
        msg: "I'm Rick James!!"
