- name: Update a ServiceNow ticket
  hosts: all

  vars:
    snow:
      id: INC0010107

  tasks:

    - name: Retrieve a specific incident by its sys_id
      servicenow.itsm.incident_info:
        number: "{{ snow.id }}"
      register: result

    - name: Update a ServiceNow ticket with a new comment
      servicenow.itsm.incident:
        number: "{{ snow.id }}"
        other:
          work_notes: "{{ message | default('nothing') }}"
          comments: "{{ message | default('nothing') }}"
        state: in_progress
      register: result

    - name: Retrieve a specific incident by its sys_id
      servicenow.itsm.incident_info:
        number: "{{ snow.id }}"
      register: result

...
