- name: Update a ServiceNow ticket
  hosts: all

  vars:
    snow:
      id: INC0010107
      text: "{{ message | default('INC0010107|nothing') }}"

  tasks:

    - debug:
        var: snow.text
    
    - debug:
        msg: "{{ snow.text | regex_replace('\|.*', '') }}"

    - name: Update a specified incident with a message
      when: message | regex_search('^INC')
      block:

        - name: Update a ServiceNow ticket with a new comment
          servicenow.itsm.incident:
            number: "{{ snow.text | regex_replace('\|.*', '') }}"
            other:
              work_notes: "Update recieved from EDA."
              comments: "{{ snow.text | regex_replace('^.*\|', '') }}"
            state: in_progress
          register: result

    - name: Update an unspecified incident with a message
      when: not message | regex_search('^INC')
      block:

        - name: Update a ServiceNow ticket with a new comment
          servicenow.itsm.incident:
            number: "{{ snow.id }}"
            other:
              work_notes: "Update recieved from EDA."
              comments: "{{ snow.text | regex_replace('^.*\|', '') }}"
            state: in_progress
          register: result

    - name: Retrieve a specific incident by its sys_id
      servicenow.itsm.incident_info:
        number: "{{ snow.id }}"
      register: result


...
