- name: Update a ServiceNow ticket
  hosts: all

  vars:
    snow:
      incident: "{{ id | default('INC0010107') }}"
      comment: "{{ message | default('No message specified.') }}"

  tasks:

    - name: Debug snow
      ansible.builtin.debug:
        var: snow

    - name: Update a ServiceNow ticket with a new comment
      servicenow.itsm.incident:
        number: "{{ snow.incident }}"
        other:
          work_notes: "Update recieved from EDA."
          comments: "{{ snow.comment }}"
        state: in_progress
      register: result

    - name: Retrieve a specific incident by its sys_id
      servicenow.itsm.incident_info:
        number: "{{ snow.incident }}"
      register: result

...
