---
- name: An EDA webhook that will submit JCL on a Z/OS System
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002

  # rules:
  #   - name: Run a JCL job on a Z/OS Mainframe
  #     condition: event.payload.message == "MERGSORT"
  #     action:
  #       run_job_template:
  #         # name: 'ZOS - Submit a JCL Job'
  #         name: 'SNOW - Create Incident'
  #         organization: 'Default'
  #
  #
  rules:
    - name: Didn't hear hello, update the SNow ticket
      condition: event.payload.message is defined
      action:
        run_job_template:
          name: 'Update SNow ticket'
          organization: 'Default'
          job_args:
            extra_vars:
              message: "{{ event.payload.message }}"

    - name: No content, complain
      condition: event.payload.message is not defined
      action:
        debug:
          msg: "You said nothing. Is that what you meant to say?"

...
