---
- name: Basic Webhook Actions
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  # To activate:
  # curl -v -H 'Content-Type: application/json' -d "{\"actionType\": \"SCALE\"}" https://eda-webhook.apps.hou.edgelab.online

  rules:
    - name: EDA - Basic Webhook Testing from EDA COntroller to AAP
      condition: event.payload.actionType == "SCALE"
      actions:
        - debug:
        - run_job_template:
            name: 'Rick James'
            organization: 'Default'
            job_args:
              extra_vars:
                ocp_dep: "{{ event['payload']['ocp_deployment_name'] }}"
                ocp_ns: "{{ event['payload']['ocp_namespace'] }}"
