---

- name: Listen for events on a webhook from ServiceNow
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:

    - name: Update ServiceNow incident
      condition: event.payload.sys_created_by == 'alex.jacocks' and event.payload.short_description is search('CREATE')
      action:
        run_job_template:
          name: 'AWS - Create an EC2 Instance'
          organization: 'Default'

    - name: Update ServiceNow incident
      condition: event.payload.sys_created_by == 'alex.jacocks' and event.payload.short_description is search('DOWN')
      action:
        run_job_template:
          name: 'Update SNow ticket'
          organization: 'Default'
          job_args:
            extra_vars:
              message: "Ansible EDA is working on it!"
              id: "{{ event.payload.number }}"

...
