---
- name: An example EDA webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.message == "Who is in my house?"
      action:
        run_job_template:
          name: 'The Rick James Playbook'
          organization: 'Default'

    - name: Run a JCL job on a Z/OS Mainframe
      condition: event.payload.message == "MERGSORT"
      action:
        run_job_template:
          # name: 'ZOS - Submit a JCL Job'
          name: 'EDA - SNOW Incident - Submit JCL'
          organization: 'Default'
