---
- name: An EDA webhook that will submit JCL on a Z/OS System
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run a JCL job on a Z/OS Mainframe
      condition: event.payload.message == "MERGSORT"
      action:
        run_job_template:
          # name: 'ZOS - Submit a JCL Job'
          name: 'SNOW - Create Incident'
          organization: 'Default'

    - name: Run a JCL job on a Z/OS Mainframe
      condition: event.payload.message == "MERGSORT"
      action:
        run_job_template:
          # name: 'ZOS - Submit a JCL Job'
          name: 'Z/OS - Submit a Job and Create SNOW Ticket'
          organization: 'Default'
